# Testing #2
# Testing #3
# Testing changesets
# Testing getKind()
# Testing getLogs()
# testing iterative for loop
# getClass() for entry.affectFiles
# Printing out multiple references getClass()
FROM ubuntu

CMD ["echo", "Hello!"]
